### ISSUE TITLE
Bluetooth: failed to open device

### ISSUE THREAD

**Issue by kappelloss** [schollz/find3-cli-scanner#18] opened 2018-07-24 11:03 UTC
After installing the new Version of find3-cli-scanner on Raspbian I get the following error...

pi@raspberrypi:~ $ find3-cli-scanner -i mon0 -device scanner-pi3 -family test                                          -server https://xxx.xxx.de -scantime 10 -bluetooth -passive -forever -no                                         -modify
2018-07-24 10:58:22 [INFO] main.go func1:179 scanning bluetooth
2018-07-24 10:58:22 [INFO] main.go func1:185 working in passive mode
2018-07-24 10:58:22 [ERROR] bluetooth.go scanBluetooth:37 Failed to open device,                                          err: %sno supported devices available

**Comment by schollz** [comment] 2018-07-24 12:54
You should be using `sudo ...`.

Also, what version of Raspberry Pi do you have? Are you sure it has bluetooth?

**Comment by kappelloss** [comment] 2018-07-24 13:11
I have tried with using "sudo" without any luck...
I am using the Pi Zero W and my workaround was to skip back to Commit d0af2e3, which now works perfectly...

**Comment by schollz** [comment] 2018-07-24 13:21
Can you describe more about what didn't work and why it does work?

I have a Raspberry Pi 3 with the brand new raspbian and the latest version (d7edff42e6bbe15c06a3cdb30fdbb3fc9d4f3ea7) works great:

```
sudo ./find3-cli-scanner -f z -d z --server localhost -debug -bluetooth -s 5
2018-07-24 13:20:03 [INFO] main.go func1:179 scanning bluetooth
2018-07-24 13:20:03 [DEBUG] bluetooth.go scanBluetooth:31 scanning bluetooth
2018-07-24 13:20:03 [DEBUG] bluetooth.go onStateChanged:17 gatt powered on
2018-07-24 13:20:08 [DEBUG] bluetooth.go scanBluetooth:44 bluetooth scan finished
2018-07-24 13:20:08 [DEBUG] main.go basicCapture:332 {
 "t": 1532438403235,
 "f": "z",
 "d": "z",
 "s": {
  "bluetooth": {
   "28:14:f5:35:b7:fe": -93,
   "78:e4:2a:14:63:a6": -75,
   "88:c6:26:ba:65:1f": -66,
   "e4:f0:42:92:87:d7": -72
  }
 },
 "gps": {}
}
2018-07-24 13:20:08 [DEBUG] server-main.go postData:47 posting data
```

**Comment by kappelloss** [comment] 2018-07-24 13:43
I just installed the newest Raspbian on a Raspberry Pi Zero W and executed the following commands before I followed your install tutorial:
1. sudo rpi-update
2. sudo apt-get update
3. sudo apt-get upgrade

By the way there is another strange thing that I noticed...
When I am adding the -bluetooth flag than the scanner only scans for bluetooth and not any longer for wifi... So I rolled back to 300e659 and everything works like a charm now...

Maybe I have to say that I am using the nexmon driver for passix wifi scanning instead of an extra wifi card...

**Comment by schollz** [comment] 2018-07-24 13:48
So did the bluetooth work with the newest raspbian?

> When I am adding the -bluetooth flag than the scanner only scans for bluetooth and not any longer for wifi...

This is a new feature, not a bug. To scan for wifi+bluetooth you should do `-wifi -bluetooth`. To scan just one or the other, you just use one of the flags.

**Comment by kappelloss** [comment] 2018-07-24 13:57
No the bluetooth does not work with the newst raspbian...
Sorry man that I tought it is an bug (doesn't know that I have to add the -wifi flag), but I am happy that you added this feature (some days ago I asked you for this...) :D

**Comment by schollz** [comment] 2018-07-24 15:08
@kappelloss I'm sorry I have to ask this, but are you at all associated with https://github.com/Thomas499 ? If not, may I know what you are using FIND3 for, and can you also let me know if you are part of a company that is using FIND3?

I've had issues with several users (see https://github.com/schollz/find3/issues/93 and https://github.com/schollz/find3/issues/66#issuecomment-382998197) who create accounts just for the purpose of create issues and having me solve them. It turns out these particular users were working in a company. They were not interested in contributing to open-source, but only interested in extracting free support and free bug fixes.

Your account looks very similar to theirs - you joined in late April and have almost entirely been posting issues on FIND3. This has raised red flags for me and I can't continue to work on your issues until I've figured out your relationship to FIND, sorry.

For the record, I am happy to add new features and bug fixes for companies, but I have to do it through consulting. I have a good rate and I can do things much faster through consulting, if interested, email me at zack.scholl@gmail.com.

**Comment by schollz** [comment] 2018-07-25 13:48
Okay, closing this because its not a reproducible bug and user might be unresponsive.

**Closed by schollz** 2018-07-25 13:48 UTC
Labels: needmoreinformation
